// import { createSlice, createAsyncThunk } from "@reduxjs/toolkit";
// import { getalldatafun } from "../Helper/CredOparations";
// import axios from "axios";


// // asynchronous function with createAsyncThunk
// export const datasAsync = createAsyncThunk("data/fetchDaa", async (amount) => {
//   const response = await axios.get("http://localhost:5000/admin/getallDeteals").then((responce) => {
//     return responce.data.data;
//   });
//   return response;
// });

// const initialState = {
//   state: "",
// };
// const dataSlice = createSlice({
//   name: "fechdata",
//   initialState,
//   reducers: {},
//   // data actions generated by createAsyncThunk or in other slices.
//   extraReducers: (builder) => {
//     console.log('builder',builder);
//     builder
//       .addCase(datasAsync.pending, (state, action) => {
//         // console.log("pending", action, "state", state);
//         state.status = "loading";
//       })
//       .addCase(datasAsync.fulfilled, (state, action) => {
//         // console.log("action", action);
//         state.status = "dataindatabase";
//         state.value = action.payload;
//       });
//   },
// });

// export const {} = dataSlice.actions;
// export default dataSlice.reducer;
